name: sk-project
functions:
- name: gen-iris
  spec:
    kind: job
    metadata:
      name: gen-iris
      tag: ''
      project: sk-project
      categories: []
    spec:
      command: ''
      args: []
      env: []
      default_handler: ''
      description: ''
      build:
        functionSourceCode: IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlciBvbiAyMDIwLTA0LTEwIDIwOjUwCgppbXBvcnQgb3MKZnJvbSBza2xlYXJuLmRhdGFzZXRzIGltcG9ydCBsb2FkX2lyaXMKZnJvbSBza2xlYXJuLm1vZGVsX3NlbGVjdGlvbiBpbXBvcnQgdHJhaW5fdGVzdF9zcGxpdAppbXBvcnQgbnVtcHkgYXMgbnAKZnJvbSBza2xlYXJuLm1ldHJpY3MgaW1wb3J0IGFjY3VyYWN5X3Njb3JlCmZyb20gbWxydW4uYXJ0aWZhY3RzIGltcG9ydCBUYWJsZUFydGlmYWN0LCBQbG90QXJ0aWZhY3QKaW1wb3J0IHBhbmRhcyBhcyBwZAoKZGVmIGlyaXNfZ2VuZXJhdG9yKGNvbnRleHQsIGZvcm1hdD0nY3N2Jyk6CiAgICBpcmlzID0gbG9hZF9pcmlzKCkKICAgIGlyaXNfZGF0YXNldCA9IHBkLkRhdGFGcmFtZShkYXRhPWlyaXMuZGF0YSwgY29sdW1ucz1pcmlzLmZlYXR1cmVfbmFtZXMpCiAgICBpcmlzX2xhYmVscyA9IHBkLkRhdGFGcmFtZShkYXRhPWlyaXMudGFyZ2V0LCBjb2x1bW5zPVsnbGFiZWwnXSkKICAgIGlyaXNfZGF0YXNldCA9IHBkLmNvbmNhdChbaXJpc19kYXRhc2V0LCBpcmlzX2xhYmVsc10sIGF4aXM9MSkKICAgIAogICAgY29udGV4dC5sb2dnZXIuaW5mbygnc2F2aW5nIGlyaXMgZGF0YWZyYW1lIHRvIHt9Jy5mb3JtYXQoY29udGV4dC5hcnRpZmFjdF9wYXRoKSkKICAgIGNvbnRleHQubG9nX2RhdGFzZXQoJ2lyaXNfZGF0YXNldCcsIGRmPWlyaXNfZGF0YXNldCwgZm9ybWF0PWZvcm1hdCwgaW5kZXg9RmFsc2UpCgo=
        base_image: mlrun/mlrun
        commands:
        - pip install sklearn
        - pip install pyarrow
- url: hub://describe
  name: describe
- url: hub://sklearn_classifier
  name: train
- url: hub://test_classifier
  name: test
- url: hub://model_server
  name: serving
- url: hub://model_server_tester
  name: live_tester
workflows:
- name: main
  path: workflow.py
artifacts: []
